# Generated by Django 5.0.6 on 2024-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar_actualizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='fecha_actualizacion',
            field=models.DateField(max_length=255),
        ),
    ]
