# Generated by Django 5.0.6 on 2024-05-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importar_actualizacion', '0003_alter_bodega_fecha_ultima_actualizacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bodega',
            new_name='BodegaModel',
        ),
        migrations.RenameModel(
            old_name='Enofilo',
            new_name='EnofiloModel',
        ),
        migrations.RenameModel(
            old_name='Maridaje',
            new_name='MaridajeModel',
        ),
        migrations.RenameModel(
            old_name='Siguiendo',
            new_name='SiguiendoModel',
        ),
        migrations.RenameModel(
            old_name='TipoUva',
            new_name='TipoUvaModel',
        ),
        migrations.RenameModel(
            old_name='Varietal',
            new_name='VarietalModel',
        ),
        migrations.RenameModel(
            old_name='Vino',
            new_name='VinoModel',
        ),
    ]
