# Generated by Django 5.0.6 on 2024-05-28 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar_actualizacion', '0004_rename_bodega_bodegamodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinomodel',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='importar_actualizacion.bodegamodel'),
        ),
    ]
