# Generated by Django 5.0.6 on 2024-05-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar_actualizacion', '0005_vinomodel_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='varietalmodel',
            name='tipo_uva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='importar_actualizacion.tipouvamodel'),
        ),
        migrations.AlterField(
            model_name='vinomodel',
            name='fecha_actualizacion',
            field=models.DateField(),
        ),
    ]
