# Generated by Django 5.0.6 on 2024-05-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar_actualizacion', '0006_varietalmodel_tipo_uva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinomodel',
            name='maridaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='importar_actualizacion.maridajemodel'),
        ),
        migrations.AddField(
            model_name='vinomodel',
            name='varietal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='importar_actualizacion.varietalmodel'),
        ),
    ]
